apiVersion: v1
kind: Service
metadata:
  name: car-stats-service
  labels:
    app: car-stats
spec:
  selector:
    app: car-stats
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  type: ClusterIP